%sql
SELECT DISTINCT
MD5(
CONCAT(
LOWER(TRIM(s.MQP_C_OPPORTUNITY_ID)),
'_1_109'
)
) AS QBE_HASH_OPPTY_ID,
'109' AS REC_SRC_NM,
CURRENT_TIMESTAMP AS LD_DT,
CONCAT(
LOWER(TRIM(s.MQP_C_OPPORTUNITY_ID)),
'_1'
) AS OPPTY_ID,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM dsi_dev.silver_oct16.qot_dtl s
WHERE s.MQP_C_OPPORTUNITY_ID IS NOT NULL
AND TRIM(s.MQP_C_OPPORTUNITY_ID) <> ''
AND s.MQP_PRODUCT_CODE = 'AV';
