%sql
WITH QOT_SRC AS
(
    SELECT
        Q.*,

        LOWER(
            CONCAT(
                TRIM(CAST(Q.MQP_ENTITY_REFERENCE AS STRING)),
                '_',
                TRIM(CAST(Q.MQP_DATE_MODIFIED AS STRING))
            )
        ) AS STD_QOT_ID

    FROM dsi_dev.silver_oct16.QOT_DTL Q

    WHERE Q.MQP_PRODUCT_CODE = 'AV'
),

QOT_LINKED AS
(
    SELECT
        HQ.QBE_HASH_QOT_ID,
        QS.*

    FROM QOT_SRC QS

    INNER JOIN dsi_dev.adv_db_majescoic.HUB_QOT HQ
        ON LOWER(TRIM(HQ.QOT_ID)) = QS.STD_QOT_ID
       AND HQ.REC_SRC_NM = '109'

    LEFT JOIN dsi_dev.adv_db_majescoic.SAT_QOT_DTL SQD
        ON HQ.QBE_HASH_QOT_ID = SQD.QBE_HASH_QOT_ID
       AND SQD.REC_SRC_NM = '109'

    WHERE SQD.QBE_HASH_QOT_ID IS NULL
)

SELECT

    QBE_HASH_QOT_ID,

    CURRENT_TIMESTAMP AS LD_DT,

    MQP_ENTITY_REFERENCE AS REF_ID,

    CAST(NULL AS TIMESTAMP) AS LD_END_DT,

    '109' AS REC_SRC_NM,

    MQP_POLICY_NUMBER AS PLCY_NBR,

    MQP_EFFECTIVE_DATE AS EFF_DT,

    MQP_EXPIRATION_DATE AS EXPRN_DT,

    MQP_DISPLAY_POLICY_NUMBER AS ORGNL_PLCY_NBR,

    MQP_RISK_STATE AS CNTRL_ST_CD,

    CAST(NULL AS STRING) AS AUDT_FLG,

    MQP_C_POLICY_TYPE AS PLCY_TP_CD,

    CAST(NULL AS STRING) AS PREM_WVD_FLG,

    MES_ENTITY_STATUS AS QOT_STS_CD,

    MQP_RENEWAL_INDICATOR AS NEW_RNWL_FLG,

    MQP_BOOKING_STATUS AS BKNG_STS_CD,

    MQP_C_IS_QUOTA_SHARE AS COINS_FLG,

    MQP_OLD_ENTITY_REFERENCE AS PREV_PLCY_NBR,

    MQP_PRODUCT_CODE AS PROD_CD,

    MQP_REVISION_NUMBER AS REVSN_NBR,

    MQP_PROGRAM_CODE AS PGM_CD,

    MQP_MARKET_SEGMENT_CODE AS MKT_SGMT_CD,

    MQP_MARKET_GROUP_DESCRIPTION AS MKT_SGMT_DESCR,

    MQP_RENEWAL_COUNTER AS RNWL_CNT,

    MQP_CANCEL_METHOD_DESC AS CANCTN_MTHD_DESCR,

    MQP_BOOKING_DATE AS BKNG_DT,

    MQP_BINDER_FLAG AS BNDR_FLG,

    MQP_PRODUCT_NAME AS PROD_NM,

    LPPC_C_TAIL_DATE AS TAIL_DT,

    MQP_CANCEL_CODE AS CANCTN_CD,

    MQP_CANCEL_DESCRIPTION AS CANCTN_DESCR,

    MQP_CANCEL_METHOD AS CANCTN_MTHD_CD,

    MQP_C_WINS_POLICY_NUMBER AS SRC_PLCY_NBR,

    MQP_C_PAPER_TYPE_DESC AS ADMTD_NON_ADMTD_FLG,

    MQP_C_QUOTA_POSITION AS COINS_SHR_PCT,

    CAST(NULL AS STRING) AS NON_RNWL_RSN_DESCR,

    MQP_LOSE_REASON_CODE AS QOT_STS_RSN_CD,

    MQP_C_LOST_REASON_DETAILS AS QOT_STS_RSN_TXT,

    MQP_NOT_WRITTEN_REASON_DESC AS NOT_WRTN_RSN_TXT,

    MQP_NOT_WRITTEN_REASON_CODE AS NOT_WRTN_RSN_CD,

    CAST(NULL AS STRING) AS NOT_WRTN_RSN_DESCR,

    COALESCE(
        MQP_NOT_WRITTEN_LOSE_CARRIER,
        MQP_LOSE_CARRIER
    ) AS WNNG_CARR_NM,

    CAST(NULL AS STRING) AS PGM_DESCR,

    CAST(NULL AS STRING) AS PLCY_STRC_DESCR,

    CAST(NULL AS STRING) AS PLCY_STRC_CD,

    CAST(NULL AS STRING) AS RETRO_ENDRSMT_FLG,

    CAST(NULL AS STRING) AS AUDT_FREQ_DESCR,

    CAST(NULL AS DATE) AS AUDT_STRT_DT,

    CAST(NULL AS DATE) AS AUDT_END_DT,

    CAST(NULL AS STRING) AS CANCTN_ST_CD,

    CAST(NULL AS STRING) AS AUDT_EXPSR_TP_CD,

    CAST(NULL AS STRING) AS AUDTR_CD,

    CAST(NULL AS STRING) AS CANC_OTHR_RSN_DESCR,

    MQP_DATE_MODIFIED AS SRC_EFF_DT,

    CAST(NULL AS TIMESTAMP) AS SRC_EXPRN_DT,

    0 AS ERR_FLG,

    '0' AS ERR_CD

FROM QOT_LINKED;
