%sql
SELECT DISTINCT
MD5(
CONCAT(
LOWER(TRIM(BUSINESSNAME)),
'_',
LOWER(TRIM(PARTY_TYPE)),
'_109'
)
) AS QBE_HASH_PRTY_ID,
CURRENT_TIMESTAMP AS LD_DT,
'109' AS REC_SRC_NM,
LOWER(TRIM(BUSINESSNAME)) AS PRTY_ID,
CASE
WHEN UPPER(TRIM(PARTY_TYPE)) = 'PERSON'
THEN 'Person'
WHEN UPPER(TRIM(PARTY_TYPE)) = 'ORGANIZATION'
THEN 'Organization'
ELSE PARTY_TYPE
END AS PRTY_TP_CD,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM dsi_dev.silver_oct16.party
WHERE BUSINESSNAME IS NOT NULL
AND MQP_PRODUCT_CODE = 'AV'
AND TRIM(BUSINESSNAME) <> '';
