SELECT DISTINCT
MD5(
CONCAT(
LOWER(
CONCAT_WS('_',
COALESCE(TRIM(PA.MAD_LINE_1),''),
COALESCE(TRIM(PA.MAD_LINE_2),''),
COALESCE(TRIM(PA.MAD_CITY),''),
COALESCE(TRIM(PA.MAD_COUNTY),''),
COALESCE(TRIM(PA.MAD_STATE_CODE),''),
COALESCE(TRIM(PA.MAD_COUNTRY),''),
COALESCE(TRIM(PA.MAD_ZIP_CODE),'')
)
),
'_109'
)
) AS QBE_HASH_CNTCT_PNT_ID,
CURRENT_TIMESTAMP AS LD_DT,
'109' AS REC_SRC_NM,
LOWER(
CONCAT_WS('_',
COALESCE(TRIM(PA.MAD_LINE_1),''),
COALESCE(TRIM(PA.MAD_LINE_2),''),
COALESCE(TRIM(PA.MAD_CITY),''),
COALESCE(TRIM(PA.MAD_COUNTY),''),
COALESCE(TRIM(PA.MAD_STATE_CODE),''),
COALESCE(TRIM(PA.MAD_COUNTRY),''),
COALESCE(TRIM(PA.MAD_ZIP_CODE),'')
)
) AS CNTCT_PNT_ID,
'Physical_Address' AS CNTCT_PNT_TP_CD,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM dsi_dev.silver_oct16.PHYS_ADDR PA
LEFT JOIN dsi_dev.adv_db_majescoic.hub_cntct_pnt H
ON LOWER(
CONCAT_WS('_',
COALESCE(TRIM(PA.MAD_LINE_1),''),
COALESCE(TRIM(PA.MAD_LINE_2),''),
COALESCE(TRIM(PA.MAD_CITY),''),
COALESCE(TRIM(PA.MAD_COUNTY),''),
COALESCE(TRIM(PA.MAD_STATE_CODE),''),
COALESCE(TRIM(PA.MAD_COUNTRY),''),
COALESCE(TRIM(PA.MAD_ZIP_CODE),'')
)
) = LOWER(H.CNTCT_PNT_ID)
AND H.REC_SRC_NM = '109'
WHERE PA.MAD_LINE_1 IS NOT NULL AND MQP_PRODUCT_CODE ='AV'
AND H.CNTCT_PNT_ID IS NULL;
