SELECT DISTINCT
MD5(
CONCAT(
LOWER(
CONCAT(
TRIM(MQP_DISPLAY_POLICY_NUMBER),
'_',
CAST(MQP_EFFECTIVE_DATE AS STRING)
)
),
'_109'
)
) AS QBE_HASH_PLCY_ID,
CURRENT_TIMESTAMP AS LD_DT,
'109' AS REC_SRC_NM,
LOWER(
CONCAT(
TRIM(MQP_DISPLAY_POLICY_NUMBER),
'_',
CAST(MQP_EFFECTIVE_DATE AS STRING)
)
) AS PLCY_ID,
NULL AS PROD_TP,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM dsi_dev.silver_oct16.PLCY_DTL
WHERE MQP_DISPLAY_POLICY_NUMBER IS NOT NULL
AND MQP_PRODUCT_CODE = 'AV'
AND MQP_EFFECTIVE_DATE IS NOT NULL;
