SELECT DISTINCT
MD5(
CONCAT(
LOWER(TRIM(MCN_E_MAIL)),
'_109'
)
) AS QBE_HASH_CNTCT_PNT_ID,
CURRENT_TIMESTAMP AS LD_DT,
'109' AS REC_SRC_NM,
LOWER(TRIM(MCN_E_MAIL)) AS CNTCT_PNT_ID,
'Electronic_Address' AS CNTCT_PNT_TP_CD,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM dsi_dev.silver_oct16.ELEC_ADDR
WHERE MCN_E_MAIL IS NOT NULL AND MQP_PRODUCT_CODE='AV'
AND TRIM(MCN_E_MAIL) <> '';
