SELECT DISTINCT
MD5(
CONCAT(
LOWER(TRIM(LOB_CODE)),
'_109'
)
) AS QBE_HASH_LOB_ID,
CURRENT_TIMESTAMP AS LD_DT,
'109' AS REC_SRC_NM,
LOWER(TRIM(LOB_CODE)) AS LOB_ID,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM dsi_dev.silver_oct16.LOB_DTL
WHERE LOB_CODE IS NOT NULL
AND MQP_PRODUCT_CODE = 'AV'
AND TRIM(LOB_CODE) <> '';
 
