SELECT DISTINCT
MD5(
CONCAT(
LOWER(
CONCAT(
COALESCE(RPEC_C_CARRIER,''),
'_',
COALESCE(RPEC_C_QUOTA_POLICY_NUMBER,''),
'_',
COALESCE(CAST(RPEC_ID AS STRING),'')
)
),
'_109'
)
) AS QBE_HASH_COINS_PLCY_ID,
CURRENT_TIMESTAMP AS LD_DT,
'109' AS REC_SRC_NM,
LOWER(
CONCAT(
COALESCE(RPEC_C_CARRIER,''),
'_',
COALESCE(RPEC_C_QUOTA_POLICY_NUMBER,''),
'_',
COALESCE(CAST(RPEC_ID AS STRING),'')
)
) AS COINS_PLCY_ID,
NULL AS QOT_FLG,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM dsi_dev.silver_oct16.coins_plcy_dtl
WHERE RPEC_C_CARRIER IS NOT NULL AND MQP_PRODUCT_CODE = 'AV'
AND RPEC_C_QUOTA_POLICY_NUMBER IS NOT NULL
AND RPEC_ID IS NOT NULL;
 
