SELECT DISTINCT
MD5(
CONCAT(
TRIM(MCN_PHONE_1),
'_109'
)
) AS QBE_HASH_CNTCT_PNT_ID,
CURRENT_TIMESTAMP AS LD_DT,
'109' AS REC_SRC_NM,
TRIM(MCN_PHONE_1) AS CNTCT_PNT_ID,
'Phone_Number' AS CNTCT_PNT_TP_CD,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM dsi_dev.silver_oct16.PHON_NBR
WHERE MCN_PHONE_1 IS NOT NULL AND MQP_PRODUCT_CODE='AV'
AND TRIM(MCN_PHONE_1) <> '';
