SELECT DISTINCT
MD5(
CONCAT(
LOWER(
CONCAT_WS('_',
COALESCE(PRODUCT_CODE,''),
COALESCE(LOB_CODE,''),
COALESCE(C_COVERAGE_CODE,''),
COALESCE(ASLOB,''),
COALESCE(SUBLINE_CODE,''),
COALESCE(
CASE
WHEN DISP_NAME IS NOT NULL
THEN DISP_NAME
WHEN DISP_NAME IS NULL
AND CVRG_DESCR IS NOT NULL
THEN CVRG_DESCR
ELSE ''
END,
''
)
)
),
'_109'
)
) AS QBE_HASH_CVRG_ID,
'109' AS REC_SRC_NM,
CURRENT_TIMESTAMP AS LD_DT,
LOWER(
CONCAT_WS('_',
COALESCE(PRODUCT_CODE,''),
COALESCE(LOB_CODE,''),
COALESCE(C_COVERAGE_CODE,''),
COALESCE(ASLOB,''),
COALESCE(SUBLINE_CODE,''),
COALESCE(
CASE
WHEN DISP_NAME IS NOT NULL
THEN DISP_NAME
WHEN DISP_NAME IS NULL
AND CVRG_DESCR IS NOT NULL
THEN CVRG_DESCR
ELSE ''
END,
''
)
)
) AS CVRG_ID,
0 AS ERR_FLG,
'0' AS ERR_CD
FROM  dsi_dev.silver_oct16.cvrg_dtl
WHERE C_COVERAGE_CODE IS NOT NULL AND MQP_PRODUCT_CODE ='AV';
 
 
 
